CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(255) NOT NULL, 
hashed_password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
api_token VARCHAR(255) NOT NULL
);

CREATE TABLE books(
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME,
color VARCHAR(255) NOT NULL,
owner INT NOT NULL,
completed BOOLEAN NOT NULL,
checked_out BOOLEAN NOT NULL
);

CREATE TABLE checkouts(
id INT PRIMARY KEY AUTO_INCREMENT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME,
book_id INT NOT NULL,
user_id INT NOT NULL,
checked_out_at DATETIME NOT NULL,
returned_at DATETIME
);

CREATE TABLE authors(
id INT PRIMARY KEY AUTO_INCREMENT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME,
first_name VARCHAR(255),
last_name VARCHAR(255) NOT NULL
);

CREATE TABLE tags(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255)
);

CREATE TABLE books_authors(
book_id INT NOT NULL,
author_id INT NOT NULL
);

CREATE TABLE books_tags(
book_id INT NOT NULL,
tag_id INT NOT NULL
)